#print("hello world")
#print("oi")
#print("1+1")
#print('1'+'1')
#print(1+1)
#nome=input('Qual o seu nome? ')
#idade=input('Qual a sua idade? ')
#peso=input('Qual o seu peso? ')
#print (f'Meu nome é {nome}, minha idade é {idade}, e meu peso é {peso}' )
n1=int(input('digite um numero inteiro: ')) 
n2=int(input('digite outro numero inteiro: ')) 
print(f'A soma é igual a {n1+n2}')